name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        docker-compose -f docker-compose.github-ci.yml down -v --remove-orphans
        docker-compose -f docker-compose.github-ci.yml pull
        docker-compose -f docker-compose.github-ci.yml build
        docker-compose -f docker-compose.github-ci.yml up -d

    - name: Build React App
      run: |
        docker-compose -f docker-compose.github-ci.yml run --rm github-node-cli yarn install
        docker-compose -f docker-compose.github-ci.yml run --rm github-node-cli yarn build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build
        publish_branch: gh-pages